### ISSUE TITLE
Hardware link seems to be dead

### ISSUE THREAD

**Issue by AnimiVulpis** [barafael/cute-copter#1]
The link in the **Hardware** section seems to be dead:
* https://de.aliexpress.com/item/4001108687090.html?gatewayAdapt=glo2deu&spm=a2g0o.order_list.0.0.21ef5c5f4uzTWV
> Sorry, the page you requested can not be found:(

_And what's up with the weird query string? Is that really needed?_

**Comment by barafael** [comment]
Hi, thanks for reporting this!
Indeed the whole shop page is much slimmer than it was before. I don't think the articles are sold anymore. I'll mark the link as dead... this is a little sad, but on the other hand the hardware is crap anyway (which was the motivation to do this).

**Comment by barafael** [comment]
fixed in [#4c6c9fcb37eddef723eda1b0a848d45e58fd5e9d](https://github.com/barafael/cute-copter/commit/4c6c9fcb37eddef723eda1b0a848d45e58fd5e9d)
